### PR TITLE
all images optimized without any loss, using oxipng

### PR DESCRIPTION
**Pull request by Luisinhi010**
the tittle says all

### CODE REVIEW

**Comment by Luisinhi010** [comment]
I won't say the fact that some sprites are VERY big in terms of size, also, some images were optimized by more than 50% but I think the Kade's branch is still a good option for sprite optimization.

**Comment by lunarcleint** [comment]
idk about this, seems like something for a fanmade build

**Review by MemeHoovy — APPROVED** [review]

**Comment by Luisinhi010** [comment]
> idk about this, seems like something for a fanmade build

I used oxipng https://github.com/shssoichiro/oxipng to optimize all pngs. 

and I don't even know if a fanmade build will have all images exactly the same

**Comment by Randomxdp** [comment]
> > idk about this, seems like something for a fanmade build
> 
> I used oxipng https://github.com/shssoichiro/oxipng to optimize all pngs.
> 
> and I don't even know if a fanmade build will have all images exactly the same

all this does is compress the images, something like cutting of the empty places in sprites would optimize the ram usage of this mod

**Comment by Luisinhi010** [comment]
> > > idk about this, seems like something for a fanmade build
> > 
> > 
> > I used oxipng https://github.com/shssoichiro/oxipng to optimize all pngs.
> > and I don't even know if a fanmade build will have all images exactly the same
> 
> all this does is compress the images, something like cutting of the empty places in sprites would optimize the ram usage of this mod

my pc doesn't dies anymore on defeat, so i'm happy

**Pull request closed without merging**
