### PR TITLE
New save location so it doesnt overwrite over your main psych engine save file

### PR DESCRIPTION
**Pull request by trayfellow**
yeah

although this says bye bye to your old save file so that could be an issue

### CODE REVIEW

**Comment by LeanDapper** [comment]
lol?

**Comment by trayfellow** [comment]
> lol?

my gmail marked your github reply as a promotion lol

**Comment by trayfellow** [comment]
image
wait nvm we good

**Comment by Luisinhi010** [comment]
wtf? lmao

**Pull request closed without merging**
