### PR TITLE
More useful bug fixes + re-added identity crisis transition 

### PR DESCRIPTION
**Pull request by LeanDapper**
almost forgot to fix this again

### CODE REVIEW

**Comment by LeanDapper** [comment]
i fixed the title screen issue  with not being able to enter lol

**Comment by LeanDapper** [comment]
HOLD I THINK I MAY HAVE FIGURED OUT THE DOUBLE KILL LAG

**Comment by LeanDapper** [comment]
YESSSSSSSSSSSS
I FIXED IT

read the commit desc if you wanna know what was the problem lol

**Comment by biomseed** [comment]
i think it's too late clowfoe already left the internet

**Comment by LeanDapper** [comment]
> i think it's too late clowfoe already left the internet

well just incase lol

**Comment by lunarcleint** [comment]
9 minutes ago

**Comment by LeanDapper** [comment]
> 9 minutes ago

lunarcleint

**Comment by biomseed** [comment]
well well well a new commit just dropped so this might get merged

**Comment by LeanDapper** [comment]
oooo

**Pull request closed without merging**
