### PR TITLE
re-add unused sussus toogus content & some optimization i think

### PR DESCRIPTION
**Pull request by LeanDapper**

### CODE REVIEW

**Comment by jmxamongusmodder** [comment]
Hey this seems cool can i use it for a mod im making that uses v4 source?

**Comment by LeanDapper** [comment]
ok can someone else please fix the issue with the dialogue animations not working anymore please

I don't know how to fix it,,,

**Comment by LeanDapper** [comment]
filesystem hated the new path system so i had to use assets instead lol

**Comment by LeanDapper** [comment]
OK NOW IM DONE LOL

**Comment by LeanDapper** [comment]
i had to deal with renaming o2

**Comment by Pichuman100** [comment]
since you added the sussus toogus bg stuff back in do you think it would be possible you could add in the drippypop bg stuff back in? cuz like the images are still in the files right

**Comment by lunarcleint** [comment]
Mr beast

**Comment by LeanDapper** [comment]
> Mr beast

MR BEASTTTTTTTTTTTTTTTTTTTTTTT

**Comment by biomseed** [comment]
> since you added the sussus toogus bg stuff back in do you think it would be possible you could add back in the drippypop bg stuff back in? cuz like the images are still in the files right

I think the whole reason those are scrapped is because they would have to make an animation of pico taking them out

**Pull request closed without merging**
