### PR TITLE
Ram fix real

### PR DESCRIPTION
**Pull request by lunarcleint**
#### I ain't even record a speed run this time, I just made it so Paths dumps the cache when needed.

heres what the speed run timer would have looked like sorry :((

### CODE REVIEW

**Comment by LeanDapper** [comment]
aw damn

**Comment by LeanDapper** [comment]
i already kinda did this in my pull

**Comment by lunarcleint** [comment]
"9 11 was bad"

**Comment by LeanDapper** [comment]
im just gonna be mad if clow tries to merge this and mine and it ruins it

**Review by trayfellow — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Review by Luisinhi010 — APPROVED** [review]

**Pull request merged**
