### PR TITLE
major memory fixes

### PR DESCRIPTION
**Pull request by TheRealJake12**
includes Burgerballs note.hx improvements and a disclaimer in readme for people complaining about compiles

### CODE REVIEW

**Comment by TheRealJake12** [comment]
also, something I need to say. DOWNSCALE. THE. TEXTURES. Ohmygod the textures are so fuckin high res. Downscale please.

**Comment by LeanDapper** [comment]
> also, something I need to say. DOWNSCALE. THE. TEXTURES. Ohmygod the textures are so fuckin high res. Downscale please.

isnt kade already making a build that does just that lmao

**Comment by TheRealJake12** [comment]
huh didnt know. Still, its a good idea to downscale shit. 16GB ram used isnt fun

**Comment by lunarcleint** [comment]
Losing brain cells over this commit fr fr

**Comment by Luisinhi010** [comment]
fr

**Pull request closed without merging**
