### PR TITLE
[World Record] "Bug Fixing" Vs Imposter V4 Any% (81%)

### PR DESCRIPTION
**Pull request by lunarcleint**
## Fixing 9 out of the 11 bugs I documented when I played the first half of the mod.

Bugs Doc with what I did and didn't fix is labeled: [https://docs.google.com/document/d/1Puyx9nCPaY9v3MjRey8AU1Isn2CwR5rkMl69OiZm4oc/edit?usp=sharing](https://docs.google.com/document/d/1Puyx9nCPaY9v3MjRey8AU1Isn2CwR5rkMl69OiZm4oc/edit?usp=sharing)

Overall time was 23 minutes and 26 seconds, def finna improve that and think its very do able for 17 minutes.

Very cool mod guys. (the family guy and satisfying video were needed)
# W MOD <33 (VIDEO UPLOADING RN I GOT SLOW ASS WIFI)

### CODE REVIEW

**Comment by SquidBoi84** [comment]
Thank you Minecraft Steve

**Comment by lunarcleint** [comment]
ofc ofc

**Comment by FoxelTheFennic** [comment]
"this is worse than the time i speedran fixing vs impostor"
image

**Comment by Clowfoe** [comment]
thanks minecraft steve

**Pull request merged**
